server:
  port: 8083

spring:
  application.name: product-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak-demo-auth:8080/auth/realms/demo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
