version: "3"

services:
  db:
    image: postgres:13.5
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwordTest1!
      POSTGRES_DB: kc-db
    ports:
      - 5432:5432

  kc:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db
      DB_DATABASE: kc-db
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: passwordTest1!
      KEYCLOAK_HOSTNAME: keycloak-demo-auth
      KEYCLOAK_USER: kc_admin
      KEYCLOAK_PASSWORD: kc_password
    ports:
      - 8080:8080
    depends_on:
      - db
